Traceback (most recent call last):
  File "./test.py", line 3, in <module>
    print sys.argv[1]
IndexError: list index out of range
